ALTER TABLE "User"
  ALTER COLUMN "firstName" TYPE VARCHAR(100),
  ALTER COLUMN "lastName" TYPE VARCHAR(100),
  ALTER COLUMN "email" TYPE VARCHAR(320),
  ALTER COLUMN "passwordHash" TYPE VARCHAR(255),
  ALTER COLUMN "refreshTokenHash" TYPE VARCHAR(128);

ALTER TABLE "Workspace"
  ALTER COLUMN "name" TYPE VARCHAR(120),
  ALTER COLUMN "slug" TYPE VARCHAR(100),
  ALTER COLUMN "timezone" TYPE VARCHAR(100);

ALTER TABLE "Invitation"
  ALTER COLUMN "email" TYPE VARCHAR(320),
  ALTER COLUMN "tokenHash" TYPE VARCHAR(128);

ALTER TABLE "Room"
  ALTER COLUMN "name" TYPE VARCHAR(120),
  ALTER COLUMN "description" TYPE VARCHAR(1000);

ALTER TABLE "Booking"
  ALTER COLUMN "subject" TYPE VARCHAR(200);

ALTER TABLE "WorkspaceScheduleVersion"
  ALTER COLUMN "timezone" TYPE VARCHAR(100);

ALTER TABLE "OperationLog"
  ALTER COLUMN "ipAddress" TYPE VARCHAR(45);

ALTER TABLE "RateLimitSuspension"
  ALTER COLUMN "ipAddress" TYPE VARCHAR(45);

ALTER TABLE "EmailVerificationToken"
  ALTER COLUMN "tokenHash" TYPE VARCHAR(128);

ALTER TABLE "PasswordResetToken"
  ALTER COLUMN "tokenHash" TYPE VARCHAR(128);
